{% set name = "sardem" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sardem-{{ version }}.tar.gz
  sha256: 26013c89a7946673fe836830c59e78e6cd5456c23ca3ee69d508fb167cc582d0

build:
  entry_points:
    - sardem=sardem.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - python >={{ python_min }}
    - requests

test:
  imports:
    - sardem
  commands:
    - pip check
    - sardem --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scottstanie/sardem
  summary: Create upsampled DEMs for InSAR processing
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - scottstanie
