{% set name = "sardem" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sardem-{{ version }}.tar.gz
  sha256: 56ec54182144dc6517c07cd6bf218e5202ca2edfd01a416f4093e7a2beff8b05

build:
  entry_points:
    - sardem=sardem.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - requests

test:
  imports:
    - sardem
  commands:
    - pip check
    - sardem --help
  requires:
    - pip

about:
  home: https://github.com/scottstanie/sardem
  summary: Create upsampled DEMs for InSAR processing
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - scottstanie
